# Generated by Django 4.2.7 on 2025-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='encryption_method',
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
