# Generated by Django 4.2.7 on 2025-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_encrypted_content_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='encrypted_content',
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_method',
            field=models.CharField(default='AES', max_length=20),
        ),
    ]
