# Generated by Django 4.2.7 on 2025-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_encrypted_content_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_encrypted',
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='iv',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
