# Generated by Django 4.2.7 on 2025-05-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_is_encrypted_message_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_keys',
            field=models.JSONField(default=dict),
        ),
    ]
